---
abstract: 'Low level Catmandu interface to the Fedora Commons REST API'
author:
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
build_requires:
  Software::License: 0
  Test::More: 0.98
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-FedoraCommons
provides:
  Catmandu::FedoraCommons:
    file: lib/Catmandu/FedoraCommons.pm
    version: 0.271
  Catmandu::FedoraCommons::Model::addRelationship:
    file: lib/Catmandu/FedoraCommons/Model/addRelationship.pm
  Catmandu::FedoraCommons::Model::datastreamHistory:
    file: lib/Catmandu/FedoraCommons/Model/datastreamHistory.pm
  Catmandu::FedoraCommons::Model::datastreamProfile:
    file: lib/Catmandu/FedoraCommons/Model/datastreamProfile.pm
  Catmandu::FedoraCommons::Model::export:
    file: lib/Catmandu/FedoraCommons/Model/export.pm
  Catmandu::FedoraCommons::Model::findObjects:
    file: lib/Catmandu/FedoraCommons/Model/findObjects.pm
  Catmandu::FedoraCommons::Model::getDatastreamDissemination:
    file: lib/Catmandu/FedoraCommons/Model/getDatastreamDissemination.pm
  Catmandu::FedoraCommons::Model::getObjectHistory:
    file: lib/Catmandu/FedoraCommons/Model/getObjectHistory.pm
  Catmandu::FedoraCommons::Model::getObjectProfile:
    file: lib/Catmandu/FedoraCommons/Model/getObjectProfile.pm
  Catmandu::FedoraCommons::Model::getRelationships:
    file: lib/Catmandu/FedoraCommons/Model/getRelationships.pm
  Catmandu::FedoraCommons::Model::ingest:
    file: lib/Catmandu/FedoraCommons/Model/ingest.pm
  Catmandu::FedoraCommons::Model::listDatastreams:
    file: lib/Catmandu/FedoraCommons/Model/listDatastreams.pm
  Catmandu::FedoraCommons::Model::listMethods:
    file: lib/Catmandu/FedoraCommons/Model/listMethods.pm
  Catmandu::FedoraCommons::Model::modifyObject:
    file: lib/Catmandu/FedoraCommons/Model/modifyObject.pm
  Catmandu::FedoraCommons::Model::pidList:
    file: lib/Catmandu/FedoraCommons/Model/pidList.pm
  Catmandu::FedoraCommons::Model::purgeDatastream:
    file: lib/Catmandu/FedoraCommons/Model/purgeDatastream.pm
  Catmandu::FedoraCommons::Model::purgeObject:
    file: lib/Catmandu/FedoraCommons/Model/purgeObject.pm
  Catmandu::FedoraCommons::Model::purgeRelationship:
    file: lib/Catmandu/FedoraCommons/Model/purgeRelationship.pm
  Catmandu::FedoraCommons::Model::upload:
    file: lib/Catmandu/FedoraCommons/Model/upload.pm
  Catmandu::FedoraCommons::Model::validate:
    file: lib/Catmandu/FedoraCommons/Model/validate.pm
  Catmandu::FedoraCommons::Response:
    file: lib/Catmandu/FedoraCommons/Response.pm
  Catmandu::Store::FedoraCommons:
    file: lib/Catmandu/Store/FedoraCommons.pm
  Catmandu::Store::FedoraCommons::Bag:
    file: lib/Catmandu/Store/FedoraCommons.pm
  Catmandu::Store::FedoraCommons::DC:
    file: lib/Catmandu/Store/FedoraCommons/DC.pm
  Catmandu::Store::FedoraCommons::FOXML:
    file: lib/Catmandu/Store/FedoraCommons/FOXML.pm
requires:
  Catmandu: 0.05
  Data::Validate::Type: 1.004000
  Data::Validate::URI: 0.06
  HTTP::Request::Common: 6.03
  RDF::Trine: 1.003
  Test::JSON: 0.11
  XML::LibXML: 2.0014
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.271
